name: Java CI with Maven - Test, Package, and SonarQube Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build and test with Maven
        run: mvn -B package

      - name: SonarQube Analysis
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar_project_key=$(echo "${{ github.repository }}" | sed 's-/-_-')

          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey="$sonar_project_key" \
            -Dsonar.organization=CERI-M1-DevOps \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.host.url=https://sonarcloud.io
