name: Generate and Deploy Java Documentation

on:
  pull_request:
    types: [closed]
    branches:
      - main
  
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Generate Java Documentation
        run: mvn -B javadoc:javadoc

      - name: List generated documentation
        run: ls -R ./target/site/apidocs

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./target/site/apidocs

